var iphoneJson = [{
					"japan":[
						{"city":"jp","type":"iphone_7","capacity":"32","name":"iphone7","product":"MNCE2J%2FA"},
						{"city":"jp","type":"iphone_7","capacity":"128","name":"iphone7","product":"MNCK2J%2FA"},
						{"city":"jp","type":"iphone_7","capacity":"32","name":"iphone7plus","product":"MNRA2J%2FA"},
						{"city":"jp","type":"iphone_7","capacity":"128","name":"iphone7plus","product":"MN6G2J%2FA"},
						{"city":"jp","type":"iphone_8","capacity":"64","name":"iphone8","product":"MQ7A2J%2FA"},
						{"city":"jp","type":"iphone_8","capacity":"256","name":"iphone8","product":"MQ862J%2FA"},
						{"city":"jp","type":"iphone_8","capacity":"64","name":"iphone8plus","product":"MQ9M2J%2FA"},
						{"city":"jp","type":"iphone_8","capacity":"256","name":"iphone8plus","product":"MQ9Q2J%2FA"},
						{"city":"jp","type":"iphone_x","capacity":"64","name":"iphoneX","product":"MQAY2J%2FA"},
						{"city":"jp","type":"iphone_x","capacity":"256","name":"iphoneX","product":"MQC22J%2FA"}
					],
					"hongkong":[
						{"city":"hk-zh","type":"iphone_7","capacity":"32","name":"iphone7","product":"MN8H2ZP%2FA"},
						{"city":"hk-zh","type":"iphone_7","capacity":"128","name":"iphone7","product":"MN8M2ZP%2FA"},
						{"city":"hk-zh","type":"iphone_7","capacity":"32","name":"iphone7plus","product":"MNQJ2ZP%2FA"},
						{"city":"hk-zh","type":"iphone_7","capacity":"128","name":"iphone7plus","product":"MN492ZP%2FA"},
						{"city":"hk-zh","type":"iphone_8","capacity":"64","name":"iphone8","product":"MQ6M2ZP%2FA"},
						{"city":"hk-zh","type":"iphone_8","capacity":"256","name":"iphone8","product":"MQ7H2ZP%2FA"},
						{"city":"hk-zh","type":"iphone_8","capacity":"64","name":"iphone8plus","product":"MQ8F2ZP%2FA"},
						{"city":"hk-zh","type":"iphone_8","capacity":"256","name":"iphone8plus","product":"MQ8J2ZP%2FA"},
						{"city":"hk-zh","type":"iphone_x","capacity":"64","name":"iphoneX","product":"MQA62ZP%2FA"},
						{"city":"hk-zh","type":"iphone_x","capacity":"256","name":"iphoneX","product":"MQA92ZP%2FA"}
					],
					"china":[
						{"city":"cn","type":"iphone_7","capacity":"32","name":"iphone7","product":"MNGR2CH%2FA"},
						{"city":"cn","type":"iphone_7","capacity":"128","name":"iphone7","product":"MNGY2CH%2FA"},
						{"city":"cn","type":"iphone_7","capacity":"32","name":"iphone7plus","product":"MNRK2CH%2FA"},
						{"city":"cn","type":"iphone_7","capacity":"128","name":"iphone7plus","product":"MNFQ2CH%2FA"},
						{"city":"cn","type":"iphone_8","capacity":"64","name":"iphone8","product":"MQ6M2CH%2FA"},
						{"city":"cn","type":"iphone_8","capacity":"256","name":"iphone8","product":"MQ7H2CH%2FA"},
						{"city":"cn","type":"iphone_8","capacity":"64","name":"iphone8plus","product":"MQ8F2CH%2FA"},
						{"city":"cn","type":"iphone_8","capacity":"256","name":"iphone8plus","product":"MQ8J2CH%2FA"},
						{"city":"cn","type":"iphone_x","capacity":"64","name":"iphoneX","product":"MQA62CH%2FA"},
						{"city":"cn","type":"iphone_x","capacity":"256","name":"iphoneX","product":"MQA92CH%2FA"}
					],
					"us":[
						{"city":"us","type":"iphone_7","capacity":"32","name":"iphone7","product":"MN8H2LL%2FA&cppart=UNLOCKED%2FUS"},
						{"city":"us","type":"iphone_7","capacity":"128","name":"iphone7","product":"MN8M2LL%2FA&cppart=UNLOCKED%2FUS"},
						{"city":"us","type":"iphone_7","capacity":"32","name":"iphone7plus","product":"MNQJ2LL%2FA&cppart=UNLOCKED%2FUS"},
						{"city":"us","type":"iphone_7","capacity":"128","name":"iphone7plus","product":"MN492LL%2FA&cppart=UNLOCKED%2FUS"},
						{"city":"us","type":"iphone_8","capacity":"64","name":"iphone8","product":"MQ6M2LL%2FA&cppart=UNLOCKED%2FUS"},
						{"city":"us","type":"iphone_8","capacity":"256","name":"iphone8","product":"MQ7H2LL%2FA&cppart=UNLOCKED%2FUS"},
						{"city":"us","type":"iphone_8","capacity":"64","name":"iphone8plus","product":"MQ8F2LL%2FA&cppart=UNLOCKED%2FUS"},
						{"city":"us","type":"iphone_8","capacity":"256","name":"iphone8plus","product":"MQ8J2LL%2FA&cppart=UNLOCKED%2FUS"},
						{"city":"us","type":"iphone_x","capacity":"64","name":"iphoneX","product":""},
						{"city":"us","type":"iphone_x","capacity":"256","name":"iphoneX","product":""}
					]
				}]